apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: LoadBalancer  # Change this to NodePort if LoadBalancer doesn't work locally
  ports:
  - port: 80
    targetPort: 3000
  selector:
    app: hello-world
