name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and deploy to Kubernetes
        run: |
          # Build the Docker image locally in the GitHub Actions runner
          docker build -t hello-world:latest ./code
          
          # Apply Kubernetes manifests
          kubectl apply -f deploy/deployment.yaml
          kubectl apply -f deploy/service.yaml
